//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridCrudSorting.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class ExerciseRecord
    {
        public int Id { get; set; }

        [Remote("ExerciseAlreadyExists", "Exercise", HttpMethod = "POST", ErrorMessage = "Exercise already exists")]
        [StringLength(100)]
        [Required(ErrorMessage = "This field is required.")]
        public string ExerciseName { get; set; }

       
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:mm-dd-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "This field is required.")]       
        public virtual System.DateTime ExerciseDate{ get; set; }

        [Range(1,120)]
        [Required(ErrorMessage = "This field is required.")]
        public int DurationInMinutes { get; set; }
    }
}
